name: Unpublish Package

on: workflow_dispatch

jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Unpublish package
        run: npm unpublish dematrix@1.0.0-beta.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
